version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    command: foreman start -p 5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
