default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: promatch_development

test:
  <<: *default
  database: promatch_test

production:
  <<: *default
  database: promatch_production
