default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: promatch_development

test:
  <<: *default
  database: promatch_test

production:
  <<: *default
  database: promatch_production
  password: <%= ENV['PROMATCH_DATABASE_PASSWORD'] %>
